# DO NOT CHANGE THIS FILE!
# Use package.json if you need to add any commands to configure your app. For more information, check out README.md.

name: Tests
on:
  push:
    branches:
      - '*'
      - '!master'
      - '!main'
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Fetch apiUrl
        run: echo ::set-output name=apiUrl::$(jq -r .env.apiUrl cypress.json)/ping
        id: fetchApiUrl
      - name: Ensure mochawesome
        run: 'jq -r ".[\"devDependencies\"] |= (.mochawesome = \"^6.2.2\")" package.json > package.json.tmp && mv package.json.tmp package.json'
      - name: Install deps
        run: npm install
      - name: Update test reporter
        run: 'jq -M ". + {\"reporter\": \"mochawesome\", \"reporterOptions\": { \"reportDir\": \"cypress/results\", \"overwrite\": false, \"html\": false, \"json\": true }}" cypress.json > cypress.json.tmp && mv cypress.json.tmp cypress.json'
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run start
          wait-on: ${{ steps.fetchApiUrl.outputs.apiUrl }}
      - name: Fetch test results
        if: always()
        run: "echo ::set-output name=results::$(jq -r '[.results[].suites[].tests[] | {test: .title, result: .state}]' cypress/results/mochawesome.json)"
        id: fetchTestResults
      - name: Set repo env var
        if: always()
        run: echo "github_repo=$GITHUB_REPOSITORY" >> $GITHUB_ENV
      - uses: joelwmale/webhook-action@master
        if: always()
        with:
          url: https://app.devskills.co/api/assignment-auto-test-results
          body: '{"assignmentRepository": "${{ env.github_repo }}","results": [${{ steps.fetchTestResults.outputs.results }}]}'
